// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzmzbbsuqyyljgoclkwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6bXpiYnN1cXl5bGpnb2Nsa3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTU0MTEsImV4cCI6MjA3MDMzMTQxMX0.sx1QA0omUggjKHeMCskxqS6IM3TNo9t4Z-jFLbvtLm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});